// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/enums.proto
// Protobuf C++ Version: 7.36.0-dev

#ifndef common_2fenums_2eproto_2epb_2eh
#define common_2fenums_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_common_2fenums_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2fenums_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_common_2fenums_2eproto;
}  // extern "C"
namespace common {
enum Sex : int;
extern const uint32_t Sex_internal_data_[];
}  // namespace common
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::common::Sex_internal_data_>
    internal::EnumTraitsImpl::value<::common::Sex>;
}  // namespace protobuf
}  // namespace google

namespace common {
enum Sex : int {
  SEX_UNKNOW = 0,
  SEX_MAN = 1,
  SEX_WOMAN = 2,
  Sex_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Sex_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Sex_internal_data_[];
inline constexpr Sex Sex_MIN =
    static_cast<Sex>(0);
inline constexpr Sex Sex_MAX =
    static_cast<Sex>(2);
[[nodiscard]] inline bool Sex_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int Sex_ARRAYSIZE = 2 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
Sex_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(Sex) {
  return Sex_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& Sex_Name(T value) {
  static_assert(::std::is_same<T, Sex>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Sex_Name().");
  return Sex_Name(static_cast<Sex>(value));
}
template <>
[[nodiscard]] inline const ::std::string& Sex_Name(Sex value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Sex_descriptor, 0, 2>(
      static_cast<int>(value));
}
[[nodiscard]] inline bool Sex_Parse(
    ::absl::string_view name, Sex* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Sex>(Sex_descriptor(), name,
                                           value);
}
using ::google::protobuf::internal::generated_enum::AbslParseFlag;
using ::google::protobuf::internal::generated_enum::AbslUnparseFlag;

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace common


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::common::Sex> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::common::Sex>() {
  return ::common::Sex_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // common_2fenums_2eproto_2epb_2eh
