// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/enums.proto
// Protobuf C++ Version: 7.36.0-dev

#include "common/enums.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace common {
}  // namespace common
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_common_2fenums_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_common_2fenums_2eproto = nullptr;
const ::uint32_t TableStruct_common_2fenums_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* PROTOBUF_NULLABLE schemas = nullptr;
static constexpr ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const* PROTOBUF_NULLABLE
    file_message_globals = nullptr;
const char descriptor_table_protodef_common_2fenums_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022common/enums.proto\022\006common*1\n\003Sex\022\016\n\nS"
    "EX_UNKNOW\020\000\022\013\n\007SEX_MAN\020\001\022\r\n\tSEX_WOMAN\020\002b"
    "\006proto3"
};
static ::absl::once_flag descriptor_table_common_2fenums_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_common_2fenums_2eproto = {
    false,
    false,
    87,
    descriptor_table_protodef_common_2fenums_2eproto,
    "common/enums.proto",
    &descriptor_table_common_2fenums_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_message_globals,
    TableStruct_common_2fenums_2eproto::offsets,
    file_level_enum_descriptors_common_2fenums_2eproto,
    file_level_service_descriptors_common_2fenums_2eproto,
};
namespace common {
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
Sex_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_common_2fenums_2eproto);
  return file_level_enum_descriptors_common_2fenums_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Sex_internal_data_[] = {
    196608u, 0u, };
// @@protoc_insertion_point(namespace_scope)
}  // namespace common
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_common_2fenums_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
