// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: greeter.proto
#ifndef GRPC_greeter_2eproto__INCLUDED
#define GRPC_greeter_2eproto__INCLUDED

#include "greeter.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace greeter {

class Greeter final {
 public:
  static constexpr char const* service_full_name() {
    return "greeter.Greeter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SayHello(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::greeter::HelloReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::greeter::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::greeter::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::greeter::HelloReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::greeter::HelloReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::greeter::HelloReply>> LotsOfReplies(::grpc::ClientContext* context, const ::greeter::HelloRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::greeter::HelloReply>>(LotsOfRepliesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::greeter::HelloReply>> AsyncLotsOfReplies(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::greeter::HelloReply>>(AsyncLotsOfRepliesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::greeter::HelloReply>> PrepareAsyncLotsOfReplies(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::greeter::HelloReply>>(PrepareAsyncLotsOfRepliesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriterInterface< ::greeter::HelloRequest>> LotsOfGreetings(::grpc::ClientContext* context, ::greeter::HelloReply* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::greeter::HelloRequest>>(LotsOfGreetingsRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::greeter::HelloRequest>> AsyncLotsOfGreetings(::grpc::ClientContext* context, ::greeter::HelloReply* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::greeter::HelloRequest>>(AsyncLotsOfGreetingsRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::greeter::HelloRequest>> PrepareAsyncLotsOfGreetings(::grpc::ClientContext* context, ::greeter::HelloReply* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::greeter::HelloRequest>>(PrepareAsyncLotsOfGreetingsRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::greeter::HelloRequest, ::greeter::HelloReply>> BidiHello(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::greeter::HelloRequest, ::greeter::HelloReply>>(BidiHelloRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::greeter::HelloRequest, ::greeter::HelloReply>> AsyncBidiHello(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::greeter::HelloRequest, ::greeter::HelloReply>>(AsyncBidiHelloRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::greeter::HelloRequest, ::greeter::HelloReply>> PrepareAsyncBidiHello(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::greeter::HelloRequest, ::greeter::HelloReply>>(PrepareAsyncBidiHelloRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SayHello(::grpc::ClientContext* context, const ::greeter::HelloRequest* request, ::greeter::HelloReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SayHello(::grpc::ClientContext* context, const ::greeter::HelloRequest* request, ::greeter::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void LotsOfReplies(::grpc::ClientContext* context, const ::greeter::HelloRequest* request, ::grpc::ClientReadReactor< ::greeter::HelloReply>* reactor) = 0;
      virtual void LotsOfGreetings(::grpc::ClientContext* context, ::greeter::HelloReply* response, ::grpc::ClientWriteReactor< ::greeter::HelloRequest>* reactor) = 0;
      virtual void BidiHello(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::greeter::HelloRequest,::greeter::HelloReply>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::greeter::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::greeter::HelloReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::greeter::HelloReply>* LotsOfRepliesRaw(::grpc::ClientContext* context, const ::greeter::HelloRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::greeter::HelloReply>* AsyncLotsOfRepliesRaw(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::greeter::HelloReply>* PrepareAsyncLotsOfRepliesRaw(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::greeter::HelloRequest>* LotsOfGreetingsRaw(::grpc::ClientContext* context, ::greeter::HelloReply* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::greeter::HelloRequest>* AsyncLotsOfGreetingsRaw(::grpc::ClientContext* context, ::greeter::HelloReply* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::greeter::HelloRequest>* PrepareAsyncLotsOfGreetingsRaw(::grpc::ClientContext* context, ::greeter::HelloReply* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::greeter::HelloRequest, ::greeter::HelloReply>* BidiHelloRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::greeter::HelloRequest, ::greeter::HelloReply>* AsyncBidiHelloRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::greeter::HelloRequest, ::greeter::HelloReply>* PrepareAsyncBidiHelloRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SayHello(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::greeter::HelloReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::greeter::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::greeter::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::greeter::HelloReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::greeter::HelloReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::greeter::HelloReply>> LotsOfReplies(::grpc::ClientContext* context, const ::greeter::HelloRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::greeter::HelloReply>>(LotsOfRepliesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::greeter::HelloReply>> AsyncLotsOfReplies(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::greeter::HelloReply>>(AsyncLotsOfRepliesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::greeter::HelloReply>> PrepareAsyncLotsOfReplies(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::greeter::HelloReply>>(PrepareAsyncLotsOfRepliesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::greeter::HelloRequest>> LotsOfGreetings(::grpc::ClientContext* context, ::greeter::HelloReply* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::greeter::HelloRequest>>(LotsOfGreetingsRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::greeter::HelloRequest>> AsyncLotsOfGreetings(::grpc::ClientContext* context, ::greeter::HelloReply* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::greeter::HelloRequest>>(AsyncLotsOfGreetingsRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::greeter::HelloRequest>> PrepareAsyncLotsOfGreetings(::grpc::ClientContext* context, ::greeter::HelloReply* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::greeter::HelloRequest>>(PrepareAsyncLotsOfGreetingsRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::greeter::HelloRequest, ::greeter::HelloReply>> BidiHello(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::greeter::HelloRequest, ::greeter::HelloReply>>(BidiHelloRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::greeter::HelloRequest, ::greeter::HelloReply>> AsyncBidiHello(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::greeter::HelloRequest, ::greeter::HelloReply>>(AsyncBidiHelloRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::greeter::HelloRequest, ::greeter::HelloReply>> PrepareAsyncBidiHello(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::greeter::HelloRequest, ::greeter::HelloReply>>(PrepareAsyncBidiHelloRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SayHello(::grpc::ClientContext* context, const ::greeter::HelloRequest* request, ::greeter::HelloReply* response, std::function<void(::grpc::Status)>) override;
      void SayHello(::grpc::ClientContext* context, const ::greeter::HelloRequest* request, ::greeter::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void LotsOfReplies(::grpc::ClientContext* context, const ::greeter::HelloRequest* request, ::grpc::ClientReadReactor< ::greeter::HelloReply>* reactor) override;
      void LotsOfGreetings(::grpc::ClientContext* context, ::greeter::HelloReply* response, ::grpc::ClientWriteReactor< ::greeter::HelloRequest>* reactor) override;
      void BidiHello(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::greeter::HelloRequest,::greeter::HelloReply>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::greeter::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::greeter::HelloReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::greeter::HelloReply>* LotsOfRepliesRaw(::grpc::ClientContext* context, const ::greeter::HelloRequest& request) override;
    ::grpc::ClientAsyncReader< ::greeter::HelloReply>* AsyncLotsOfRepliesRaw(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::greeter::HelloReply>* PrepareAsyncLotsOfRepliesRaw(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::greeter::HelloRequest>* LotsOfGreetingsRaw(::grpc::ClientContext* context, ::greeter::HelloReply* response) override;
    ::grpc::ClientAsyncWriter< ::greeter::HelloRequest>* AsyncLotsOfGreetingsRaw(::grpc::ClientContext* context, ::greeter::HelloReply* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::greeter::HelloRequest>* PrepareAsyncLotsOfGreetingsRaw(::grpc::ClientContext* context, ::greeter::HelloReply* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::greeter::HelloRequest, ::greeter::HelloReply>* BidiHelloRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::greeter::HelloRequest, ::greeter::HelloReply>* AsyncBidiHelloRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::greeter::HelloRequest, ::greeter::HelloReply>* PrepareAsyncBidiHelloRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SayHello_;
    const ::grpc::internal::RpcMethod rpcmethod_LotsOfReplies_;
    const ::grpc::internal::RpcMethod rpcmethod_LotsOfGreetings_;
    const ::grpc::internal::RpcMethod rpcmethod_BidiHello_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SayHello(::grpc::ServerContext* context, const ::greeter::HelloRequest* request, ::greeter::HelloReply* response);
    virtual ::grpc::Status LotsOfReplies(::grpc::ServerContext* context, const ::greeter::HelloRequest* request, ::grpc::ServerWriter< ::greeter::HelloReply>* writer);
    virtual ::grpc::Status LotsOfGreetings(::grpc::ServerContext* context, ::grpc::ServerReader< ::greeter::HelloRequest>* reader, ::greeter::HelloReply* response);
    virtual ::grpc::Status BidiHello(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::greeter::HelloReply, ::greeter::HelloRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SayHello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::greeter::HelloRequest* /*request*/, ::greeter::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::greeter::HelloRequest* request, ::grpc::ServerAsyncResponseWriter< ::greeter::HelloReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_LotsOfReplies : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_LotsOfReplies() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_LotsOfReplies() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LotsOfReplies(::grpc::ServerContext* /*context*/, const ::greeter::HelloRequest* /*request*/, ::grpc::ServerWriter< ::greeter::HelloReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLotsOfReplies(::grpc::ServerContext* context, ::greeter::HelloRequest* request, ::grpc::ServerAsyncWriter< ::greeter::HelloReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_LotsOfGreetings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_LotsOfGreetings() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_LotsOfGreetings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LotsOfGreetings(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::greeter::HelloRequest>* /*reader*/, ::greeter::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLotsOfGreetings(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::greeter::HelloReply, ::greeter::HelloRequest>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(2, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_BidiHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_BidiHello() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_BidiHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BidiHello(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::greeter::HelloReply, ::greeter::HelloRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBidiHello(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::greeter::HelloReply, ::greeter::HelloRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(3, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SayHello<WithAsyncMethod_LotsOfReplies<WithAsyncMethod_LotsOfGreetings<WithAsyncMethod_BidiHello<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::greeter::HelloRequest, ::greeter::HelloReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::greeter::HelloRequest* request, ::greeter::HelloReply* response) { return this->SayHello(context, request, response); }));}
    void SetMessageAllocatorFor_SayHello(
        ::grpc::MessageAllocator< ::greeter::HelloRequest, ::greeter::HelloReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::greeter::HelloRequest, ::greeter::HelloReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::greeter::HelloRequest* /*request*/, ::greeter::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::greeter::HelloRequest* /*request*/, ::greeter::HelloReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_LotsOfReplies : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_LotsOfReplies() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::greeter::HelloRequest, ::greeter::HelloReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::greeter::HelloRequest* request) { return this->LotsOfReplies(context, request); }));
    }
    ~WithCallbackMethod_LotsOfReplies() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LotsOfReplies(::grpc::ServerContext* /*context*/, const ::greeter::HelloRequest* /*request*/, ::grpc::ServerWriter< ::greeter::HelloReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::greeter::HelloReply>* LotsOfReplies(
      ::grpc::CallbackServerContext* /*context*/, const ::greeter::HelloRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_LotsOfGreetings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_LotsOfGreetings() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackClientStreamingHandler< ::greeter::HelloRequest, ::greeter::HelloReply>(
            [this](
                   ::grpc::CallbackServerContext* context, ::greeter::HelloReply* response) { return this->LotsOfGreetings(context, response); }));
    }
    ~WithCallbackMethod_LotsOfGreetings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LotsOfGreetings(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::greeter::HelloRequest>* /*reader*/, ::greeter::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::greeter::HelloRequest>* LotsOfGreetings(
      ::grpc::CallbackServerContext* /*context*/, ::greeter::HelloReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_BidiHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_BidiHello() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackBidiHandler< ::greeter::HelloRequest, ::greeter::HelloReply>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->BidiHello(context); }));
    }
    ~WithCallbackMethod_BidiHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BidiHello(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::greeter::HelloReply, ::greeter::HelloRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::greeter::HelloRequest, ::greeter::HelloReply>* BidiHello(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_SayHello<WithCallbackMethod_LotsOfReplies<WithCallbackMethod_LotsOfGreetings<WithCallbackMethod_BidiHello<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SayHello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::greeter::HelloRequest* /*request*/, ::greeter::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_LotsOfReplies : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_LotsOfReplies() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_LotsOfReplies() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LotsOfReplies(::grpc::ServerContext* /*context*/, const ::greeter::HelloRequest* /*request*/, ::grpc::ServerWriter< ::greeter::HelloReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_LotsOfGreetings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_LotsOfGreetings() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_LotsOfGreetings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LotsOfGreetings(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::greeter::HelloRequest>* /*reader*/, ::greeter::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_BidiHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_BidiHello() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_BidiHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BidiHello(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::greeter::HelloReply, ::greeter::HelloRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SayHello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::greeter::HelloRequest* /*request*/, ::greeter::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_LotsOfReplies : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_LotsOfReplies() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_LotsOfReplies() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LotsOfReplies(::grpc::ServerContext* /*context*/, const ::greeter::HelloRequest* /*request*/, ::grpc::ServerWriter< ::greeter::HelloReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLotsOfReplies(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_LotsOfGreetings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_LotsOfGreetings() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_LotsOfGreetings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LotsOfGreetings(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::greeter::HelloRequest>* /*reader*/, ::greeter::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLotsOfGreetings(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(2, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_BidiHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_BidiHello() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_BidiHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BidiHello(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::greeter::HelloReply, ::greeter::HelloRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBidiHello(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(3, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SayHello(context, request, response); }));
    }
    ~WithRawCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::greeter::HelloRequest* /*request*/, ::greeter::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_LotsOfReplies : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_LotsOfReplies() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->LotsOfReplies(context, request); }));
    }
    ~WithRawCallbackMethod_LotsOfReplies() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LotsOfReplies(::grpc::ServerContext* /*context*/, const ::greeter::HelloRequest* /*request*/, ::grpc::ServerWriter< ::greeter::HelloReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* LotsOfReplies(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_LotsOfGreetings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_LotsOfGreetings() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->LotsOfGreetings(context, response); }));
    }
    ~WithRawCallbackMethod_LotsOfGreetings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LotsOfGreetings(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::greeter::HelloRequest>* /*reader*/, ::greeter::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* LotsOfGreetings(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_BidiHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_BidiHello() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->BidiHello(context); }));
    }
    ~WithRawCallbackMethod_BidiHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BidiHello(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::greeter::HelloReply, ::greeter::HelloRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* BidiHello(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SayHello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::greeter::HelloRequest, ::greeter::HelloReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::greeter::HelloRequest, ::greeter::HelloReply>* streamer) {
                       return this->StreamedSayHello(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::greeter::HelloRequest* /*request*/, ::greeter::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSayHello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::greeter::HelloRequest,::greeter::HelloReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SayHello<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_LotsOfReplies : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_LotsOfReplies() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::greeter::HelloRequest, ::greeter::HelloReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::greeter::HelloRequest, ::greeter::HelloReply>* streamer) {
                       return this->StreamedLotsOfReplies(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_LotsOfReplies() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status LotsOfReplies(::grpc::ServerContext* /*context*/, const ::greeter::HelloRequest* /*request*/, ::grpc::ServerWriter< ::greeter::HelloReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedLotsOfReplies(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::greeter::HelloRequest,::greeter::HelloReply>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_LotsOfReplies<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_SayHello<WithSplitStreamingMethod_LotsOfReplies<Service > > StreamedService;
};

}  // namespace greeter


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_greeter_2eproto__INCLUDED
