// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: greeter.proto

#include "greeter.pb.h"
#include "greeter.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace greeter {

static const char* Greeter_method_names[] = {
  "/greeter.Greeter/SayHello",
  "/greeter.Greeter/LotsOfReplies",
  "/greeter.Greeter/LotsOfGreetings",
  "/greeter.Greeter/BidiHello",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel, options));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SayHello_(Greeter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LotsOfReplies_(Greeter_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_LotsOfGreetings_(Greeter_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_BidiHello_(Greeter_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status Greeter::Stub::SayHello(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::greeter::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::greeter::HelloRequest, ::greeter::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void Greeter::Stub::async::SayHello(::grpc::ClientContext* context, const ::greeter::HelloRequest* request, ::greeter::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::greeter::HelloRequest, ::greeter::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void Greeter::Stub::async::SayHello(::grpc::ClientContext* context, const ::greeter::HelloRequest* request, ::greeter::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::greeter::HelloReply>* Greeter::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::greeter::HelloReply, ::greeter::HelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::greeter::HelloReply>* Greeter::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::greeter::HelloReply>* Greeter::Stub::LotsOfRepliesRaw(::grpc::ClientContext* context, const ::greeter::HelloRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::greeter::HelloReply>::Create(channel_.get(), rpcmethod_LotsOfReplies_, context, request);
}

void Greeter::Stub::async::LotsOfReplies(::grpc::ClientContext* context, const ::greeter::HelloRequest* request, ::grpc::ClientReadReactor< ::greeter::HelloReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::greeter::HelloReply>::Create(stub_->channel_.get(), stub_->rpcmethod_LotsOfReplies_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::greeter::HelloReply>* Greeter::Stub::AsyncLotsOfRepliesRaw(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::greeter::HelloReply>::Create(channel_.get(), cq, rpcmethod_LotsOfReplies_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::greeter::HelloReply>* Greeter::Stub::PrepareAsyncLotsOfRepliesRaw(::grpc::ClientContext* context, const ::greeter::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::greeter::HelloReply>::Create(channel_.get(), cq, rpcmethod_LotsOfReplies_, context, request, false, nullptr);
}

::grpc::ClientWriter< ::greeter::HelloRequest>* Greeter::Stub::LotsOfGreetingsRaw(::grpc::ClientContext* context, ::greeter::HelloReply* response) {
  return ::grpc::internal::ClientWriterFactory< ::greeter::HelloRequest>::Create(channel_.get(), rpcmethod_LotsOfGreetings_, context, response);
}

void Greeter::Stub::async::LotsOfGreetings(::grpc::ClientContext* context, ::greeter::HelloReply* response, ::grpc::ClientWriteReactor< ::greeter::HelloRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::greeter::HelloRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_LotsOfGreetings_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::greeter::HelloRequest>* Greeter::Stub::AsyncLotsOfGreetingsRaw(::grpc::ClientContext* context, ::greeter::HelloReply* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::greeter::HelloRequest>::Create(channel_.get(), cq, rpcmethod_LotsOfGreetings_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::greeter::HelloRequest>* Greeter::Stub::PrepareAsyncLotsOfGreetingsRaw(::grpc::ClientContext* context, ::greeter::HelloReply* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::greeter::HelloRequest>::Create(channel_.get(), cq, rpcmethod_LotsOfGreetings_, context, response, false, nullptr);
}

::grpc::ClientReaderWriter< ::greeter::HelloRequest, ::greeter::HelloReply>* Greeter::Stub::BidiHelloRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::greeter::HelloRequest, ::greeter::HelloReply>::Create(channel_.get(), rpcmethod_BidiHello_, context);
}

void Greeter::Stub::async::BidiHello(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::greeter::HelloRequest,::greeter::HelloReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::greeter::HelloRequest,::greeter::HelloReply>::Create(stub_->channel_.get(), stub_->rpcmethod_BidiHello_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::greeter::HelloRequest, ::greeter::HelloReply>* Greeter::Stub::AsyncBidiHelloRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::greeter::HelloRequest, ::greeter::HelloReply>::Create(channel_.get(), cq, rpcmethod_BidiHello_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::greeter::HelloRequest, ::greeter::HelloReply>* Greeter::Stub::PrepareAsyncBidiHelloRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::greeter::HelloRequest, ::greeter::HelloReply>::Create(channel_.get(), cq, rpcmethod_BidiHello_, context, false, nullptr);
}

Greeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::greeter::HelloRequest, ::greeter::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::greeter::HelloRequest* req,
             ::greeter::HelloReply* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Greeter::Service, ::greeter::HelloRequest, ::greeter::HelloReply>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::greeter::HelloRequest* req,
             ::grpc::ServerWriter<::greeter::HelloReply>* writer) {
               return service->LotsOfReplies(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[2],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< Greeter::Service, ::greeter::HelloRequest, ::greeter::HelloReply>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::greeter::HelloRequest>* reader,
             ::greeter::HelloReply* resp) {
               return service->LotsOfGreetings(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[3],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Greeter::Service, ::greeter::HelloRequest, ::greeter::HelloReply>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::greeter::HelloReply,
             ::greeter::HelloRequest>* stream) {
               return service->BidiHello(ctx, stream);
             }, this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::SayHello(::grpc::ServerContext* context, const ::greeter::HelloRequest* request, ::greeter::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::LotsOfReplies(::grpc::ServerContext* context, const ::greeter::HelloRequest* request, ::grpc::ServerWriter< ::greeter::HelloReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::LotsOfGreetings(::grpc::ServerContext* context, ::grpc::ServerReader< ::greeter::HelloRequest>* reader, ::greeter::HelloReply* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::BidiHello(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::greeter::HelloReply, ::greeter::HelloRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace greeter
#include <grpcpp/ports_undef.inc>

