// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: payment/payment.proto
// Protobuf C++ Version: 7.36.0-dev

#ifndef payment_2fpayment_2eproto_2epb_2eh
#define payment_2fpayment_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "common/message.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_payment_2fpayment_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_payment_2fpayment_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_payment_2fpayment_2eproto;
}  // extern "C"
namespace payment {
class CreateOrderReq;
struct CreateOrderReqGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern CreateOrderReqGlobalsTypeInternal CreateOrderReq_globals_;
extern const ::google::protobuf::internal::ClassDataFull CreateOrderReq_class_data_;
#else
extern const CreateOrderReqGlobalsTypeInternal CreateOrderReq_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class CreateOrderResp;
struct CreateOrderRespGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern CreateOrderRespGlobalsTypeInternal CreateOrderResp_globals_;
extern const ::google::protobuf::internal::ClassDataFull CreateOrderResp_class_data_;
#else
extern const CreateOrderRespGlobalsTypeInternal CreateOrderResp_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class Order;
struct OrderGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern OrderGlobalsTypeInternal Order_globals_;
extern const ::google::protobuf::internal::ClassDataFull Order_class_data_;
#else
extern const OrderGlobalsTypeInternal Order_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class QueryOrderReq;
struct QueryOrderReqGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern QueryOrderReqGlobalsTypeInternal QueryOrderReq_globals_;
extern const ::google::protobuf::internal::ClassDataFull QueryOrderReq_class_data_;
#else
extern const QueryOrderReqGlobalsTypeInternal QueryOrderReq_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class QueryOrderResp;
struct QueryOrderRespGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern QueryOrderRespGlobalsTypeInternal QueryOrderResp_globals_;
extern const ::google::protobuf::internal::ClassDataFull QueryOrderResp_class_data_;
#else
extern const QueryOrderRespGlobalsTypeInternal QueryOrderResp_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace payment
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace payment {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED QueryOrderReq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:payment.QueryOrderReq) */ {
 public:
  inline QueryOrderReq() : QueryOrderReq(nullptr) {}
  ~QueryOrderReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(QueryOrderReq* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(QueryOrderReq));
  }
#endif

  template <typename = void>
  explicit constexpr QueryOrderReq(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline QueryOrderReq(const QueryOrderReq& from) : QueryOrderReq(nullptr, from) {}
  inline QueryOrderReq(QueryOrderReq&& from) noexcept : QueryOrderReq(nullptr, ::std::move(from)) {}
  inline QueryOrderReq& operator=(const QueryOrderReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryOrderReq& operator=(QueryOrderReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const QueryOrderReq& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<QueryOrderReq>(&QueryOrderReq_globals_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(QueryOrderReq& a, QueryOrderReq& b) { a.Swap(&b); }
  inline void Swap(QueryOrderReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QueryOrderReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] QueryOrderReq* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<QueryOrderReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const QueryOrderReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const QueryOrderReq& from) { QueryOrderReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(QueryOrderReq* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "payment.QueryOrderReq"; }

  explicit QueryOrderReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  QueryOrderReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const QueryOrderReq& from);
  QueryOrderReq(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, QueryOrderReq&& from) noexcept
      : QueryOrderReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOrderNoFieldNumber = 1,
    kUserIdFieldNumber = 2,
    kLastIdFieldNumber = 3,
  };
  // string order_no = 1;
  void clear_order_no() ;
  [[nodiscard]] const ::std::string& order_no() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_order_no(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_order_no();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_order_no();
  void set_allocated_order_no(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_order_no() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_order_no(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_order_no();

  public:
  // int64 user_id = 2;
  void clear_user_id() ;
  [[nodiscard]] ::int64_t user_id() const;
  void set_user_id(::int64_t value);

  private:
  ::int64_t _internal_user_id() const;
  void _internal_set_user_id(::int64_t value);

  public:
  // int64 last_id = 3;
  void clear_last_id() ;
  [[nodiscard]] ::int64_t last_id() const;
  void set_last_id(::int64_t value);

  private:
  ::int64_t _internal_last_id() const;
  void _internal_set_last_id(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:payment.QueryOrderReq)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<2, 3,
                          0, 38,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const QueryOrderReq& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr order_no_;
    ::int64_t user_id_;
    ::int64_t last_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_payment_2fpayment_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Order final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:payment.Order) */ {
 public:
  inline Order() : Order(nullptr) {}
  ~Order() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Order* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Order));
  }
#endif

  template <typename = void>
  explicit constexpr Order(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline Order(const Order& from) : Order(nullptr, from) {}
  inline Order(Order&& from) noexcept : Order(nullptr, ::std::move(from)) {}
  inline Order& operator=(const Order& from) {
    CopyFrom(from);
    return *this;
  }
  inline Order& operator=(Order&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const Order& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<Order>(&Order_globals_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(Order& a, Order& b) { a.Swap(&b); }
  inline void Swap(Order* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Order* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] Order* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Order>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Order& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Order& from) { Order::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Order* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "payment.Order"; }

  explicit Order(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Order(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Order& from);
  Order(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Order&& from) noexcept
      : Order(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOrderNoFieldNumber = 2,
    kCurrencyFieldNumber = 5,
    kIdFieldNumber = 1,
    kUserIdFieldNumber = 3,
    kMoneyFieldNumber = 4,
  };
  // string order_no = 2;
  void clear_order_no() ;
  [[nodiscard]] const ::std::string& order_no() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_order_no(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_order_no();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_order_no();
  void set_allocated_order_no(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_order_no() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_order_no(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_order_no();

  public:
  // string currency = 5;
  void clear_currency() ;
  [[nodiscard]] const ::std::string& currency() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_currency(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_currency();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_currency();
  void set_allocated_currency(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_currency() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_currency(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_currency();

  public:
  // int64 id = 1;
  void clear_id() ;
  [[nodiscard]] ::int64_t id() const;
  void set_id(::int64_t value);

  private:
  ::int64_t _internal_id() const;
  void _internal_set_id(::int64_t value);

  public:
  // int64 user_id = 3;
  void clear_user_id() ;
  [[nodiscard]] ::int64_t user_id() const;
  void set_user_id(::int64_t value);

  private:
  ::int64_t _internal_user_id() const;
  void _internal_set_user_id(::int64_t value);

  public:
  // int64 money = 4;
  void clear_money() ;
  [[nodiscard]] ::int64_t money() const;
  void set_money(::int64_t value);

  private:
  ::int64_t _internal_money() const;
  void _internal_set_money(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:payment.Order)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<3, 5,
                          0, 38,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Order& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr order_no_;
    ::google::protobuf::internal::ArenaStringPtr currency_;
    ::int64_t id_;
    ::int64_t user_id_;
    ::int64_t money_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_payment_2fpayment_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED CreateOrderResp final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:payment.CreateOrderResp) */ {
 public:
  inline CreateOrderResp() : CreateOrderResp(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CreateOrderResp* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CreateOrderResp));
  }
#endif

  template <typename = void>
  explicit constexpr CreateOrderResp(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline CreateOrderResp(const CreateOrderResp& from) : CreateOrderResp(nullptr, from) {}
  inline CreateOrderResp(CreateOrderResp&& from) noexcept : CreateOrderResp(nullptr, ::std::move(from)) {}
  inline CreateOrderResp& operator=(const CreateOrderResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateOrderResp& operator=(CreateOrderResp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const CreateOrderResp& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<CreateOrderResp>(&CreateOrderResp_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CreateOrderResp& a, CreateOrderResp& b) { a.Swap(&b); }
  inline void Swap(CreateOrderResp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateOrderResp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] CreateOrderResp* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<CreateOrderResp>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const CreateOrderResp& from) { ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from); }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const CreateOrderResp& from) { ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from); }

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "payment.CreateOrderResp"; }

  explicit CreateOrderResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CreateOrderResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CreateOrderResp& from);
  CreateOrderResp(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CreateOrderResp&& from) noexcept
      : CreateOrderResp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:payment.CreateOrderResp)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 0,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_payment_2fpayment_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED CreateOrderReq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:payment.CreateOrderReq) */ {
 public:
  inline CreateOrderReq() : CreateOrderReq(nullptr) {}
  ~CreateOrderReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CreateOrderReq* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CreateOrderReq));
  }
#endif

  template <typename = void>
  explicit constexpr CreateOrderReq(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline CreateOrderReq(const CreateOrderReq& from) : CreateOrderReq(nullptr, from) {}
  inline CreateOrderReq(CreateOrderReq&& from) noexcept : CreateOrderReq(nullptr, ::std::move(from)) {}
  inline CreateOrderReq& operator=(const CreateOrderReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateOrderReq& operator=(CreateOrderReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const CreateOrderReq& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<CreateOrderReq>(&CreateOrderReq_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CreateOrderReq& a, CreateOrderReq& b) { a.Swap(&b); }
  inline void Swap(CreateOrderReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateOrderReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] CreateOrderReq* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CreateOrderReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CreateOrderReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CreateOrderReq& from) { CreateOrderReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CreateOrderReq* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "payment.CreateOrderReq"; }

  explicit CreateOrderReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CreateOrderReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CreateOrderReq& from);
  CreateOrderReq(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CreateOrderReq&& from) noexcept
      : CreateOrderReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOrderNoFieldNumber = 1,
    kCurrencyFieldNumber = 4,
    kUserIdFieldNumber = 2,
    kMoneyFieldNumber = 3,
  };
  // string order_no = 1;
  void clear_order_no() ;
  [[nodiscard]] const ::std::string& order_no() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_order_no(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_order_no();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_order_no();
  void set_allocated_order_no(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_order_no() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_order_no(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_order_no();

  public:
  // string currency = 4;
  void clear_currency() ;
  [[nodiscard]] const ::std::string& currency() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_currency(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_currency();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_currency();
  void set_allocated_currency(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_currency() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_currency(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_currency();

  public:
  // int64 user_id = 2;
  void clear_user_id() ;
  [[nodiscard]] ::int64_t user_id() const;
  void set_user_id(::int64_t value);

  private:
  ::int64_t _internal_user_id() const;
  void _internal_set_user_id(::int64_t value);

  public:
  // int64 money = 3;
  void clear_money() ;
  [[nodiscard]] ::int64_t money() const;
  void set_money(::int64_t value);

  private:
  ::int64_t _internal_money() const;
  void _internal_set_money(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:payment.CreateOrderReq)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<2, 4,
                          0, 47,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CreateOrderReq& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr order_no_;
    ::google::protobuf::internal::ArenaStringPtr currency_;
    ::int64_t user_id_;
    ::int64_t money_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_payment_2fpayment_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED QueryOrderResp final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:payment.QueryOrderResp) */ {
 public:
  inline QueryOrderResp() : QueryOrderResp(nullptr) {}
  ~QueryOrderResp() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(QueryOrderResp* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(QueryOrderResp));
  }
#endif

  template <typename = void>
  explicit constexpr QueryOrderResp(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline QueryOrderResp(const QueryOrderResp& from) : QueryOrderResp(nullptr, from) {}
  inline QueryOrderResp(QueryOrderResp&& from) noexcept : QueryOrderResp(nullptr, ::std::move(from)) {}
  inline QueryOrderResp& operator=(const QueryOrderResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryOrderResp& operator=(QueryOrderResp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const QueryOrderResp& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<QueryOrderResp>(&QueryOrderResp_globals_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(QueryOrderResp& a, QueryOrderResp& b) { a.Swap(&b); }
  inline void Swap(QueryOrderResp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QueryOrderResp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] QueryOrderResp* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<QueryOrderResp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const QueryOrderResp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const QueryOrderResp& from) { QueryOrderResp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(QueryOrderResp* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "payment.QueryOrderResp"; }

  explicit QueryOrderResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  QueryOrderResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const QueryOrderResp& from);
  QueryOrderResp(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, QueryOrderResp&& from) noexcept
      : QueryOrderResp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kListFieldNumber = 1,
    kHasMoreFieldNumber = 2,
  };
  // repeated .payment.Order list = 1;
  [[nodiscard]] int list_size()
      const;
  private:
  int _internal_list_size() const;

  public:
  void clear_list() ;
  [[nodiscard]] const ::payment::Order& list(int index) const;
  [[nodiscard]] ::payment::Order* PROTOBUF_NONNULL mutable_list(int index);
  ::payment::Order* PROTOBUF_NONNULL add_list();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::payment::Order>&
  list() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::payment::Order>* PROTOBUF_NONNULL
  mutable_list();

  private:
  const ::google::protobuf::RepeatedPtrField<::payment::Order>& _internal_list() const;
  ::google::protobuf::RepeatedPtrField<::payment::Order>* PROTOBUF_NONNULL _internal_mutable_list();

  public:
  // bool has_more = 2;
  void clear_has_more() ;
  [[nodiscard]] bool has_more() const;
  void set_has_more(bool value);

  private:
  bool _internal_has_more() const;
  void _internal_set_has_more(bool value);

  public:
  // @@protoc_insertion_point(class_scope:payment.QueryOrderResp)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          1, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const QueryOrderResp& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::payment::Order > list_;
    bool has_more_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_payment_2fpayment_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CreateOrderReq

// string order_no = 1;
inline void CreateOrderReq::clear_order_no() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_no_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& CreateOrderReq::order_no() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:payment.CreateOrderReq.order_no)
  return _internal_order_no();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CreateOrderReq::set_order_no(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.order_no_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:payment.CreateOrderReq.order_no)
}
inline ::std::string* PROTOBUF_NONNULL CreateOrderReq::mutable_order_no()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_order_no();
  // @@protoc_insertion_point(field_mutable:payment.CreateOrderReq.order_no)
  return _s;
}
inline const ::std::string& CreateOrderReq::_internal_order_no() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.order_no_.Get();
}
inline void CreateOrderReq::_internal_set_order_no(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_no_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CreateOrderReq::_internal_mutable_order_no() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.order_no_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CreateOrderReq::release_order_no() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:payment.CreateOrderReq.order_no)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.order_no_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.order_no_.Set("", GetArena());
  }
  return released;
}
inline void CreateOrderReq::set_allocated_order_no(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.order_no_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.order_no_.IsDefault()) {
    _impl_.order_no_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:payment.CreateOrderReq.order_no)
}

// int64 user_id = 2;
inline void CreateOrderReq::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::int64_t CreateOrderReq::user_id() const {
  // @@protoc_insertion_point(field_get:payment.CreateOrderReq.user_id)
  return _internal_user_id();
}
inline void CreateOrderReq::set_user_id(::int64_t value) {
  _internal_set_user_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:payment.CreateOrderReq.user_id)
}
inline ::int64_t CreateOrderReq::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_;
}
inline void CreateOrderReq::_internal_set_user_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = value;
}

// int64 money = 3;
inline void CreateOrderReq::clear_money() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.money_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::int64_t CreateOrderReq::money() const {
  // @@protoc_insertion_point(field_get:payment.CreateOrderReq.money)
  return _internal_money();
}
inline void CreateOrderReq::set_money(::int64_t value) {
  _internal_set_money(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:payment.CreateOrderReq.money)
}
inline ::int64_t CreateOrderReq::_internal_money() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.money_;
}
inline void CreateOrderReq::_internal_set_money(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.money_ = value;
}

// string currency = 4;
inline void CreateOrderReq::clear_currency() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.currency_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& CreateOrderReq::currency() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:payment.CreateOrderReq.currency)
  return _internal_currency();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CreateOrderReq::set_currency(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.currency_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:payment.CreateOrderReq.currency)
}
inline ::std::string* PROTOBUF_NONNULL CreateOrderReq::mutable_currency()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_currency();
  // @@protoc_insertion_point(field_mutable:payment.CreateOrderReq.currency)
  return _s;
}
inline const ::std::string& CreateOrderReq::_internal_currency() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.currency_.Get();
}
inline void CreateOrderReq::_internal_set_currency(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.currency_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CreateOrderReq::_internal_mutable_currency() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.currency_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CreateOrderReq::release_currency() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:payment.CreateOrderReq.currency)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.currency_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.currency_.Set("", GetArena());
  }
  return released;
}
inline void CreateOrderReq::set_allocated_currency(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.currency_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.currency_.IsDefault()) {
    _impl_.currency_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:payment.CreateOrderReq.currency)
}

// -------------------------------------------------------------------

// CreateOrderResp

// -------------------------------------------------------------------

// QueryOrderReq

// string order_no = 1;
inline void QueryOrderReq::clear_order_no() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_no_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& QueryOrderReq::order_no() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:payment.QueryOrderReq.order_no)
  return _internal_order_no();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void QueryOrderReq::set_order_no(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.order_no_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:payment.QueryOrderReq.order_no)
}
inline ::std::string* PROTOBUF_NONNULL QueryOrderReq::mutable_order_no()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_order_no();
  // @@protoc_insertion_point(field_mutable:payment.QueryOrderReq.order_no)
  return _s;
}
inline const ::std::string& QueryOrderReq::_internal_order_no() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.order_no_.Get();
}
inline void QueryOrderReq::_internal_set_order_no(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_no_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL QueryOrderReq::_internal_mutable_order_no() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.order_no_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE QueryOrderReq::release_order_no() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:payment.QueryOrderReq.order_no)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.order_no_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.order_no_.Set("", GetArena());
  }
  return released;
}
inline void QueryOrderReq::set_allocated_order_no(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.order_no_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.order_no_.IsDefault()) {
    _impl_.order_no_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:payment.QueryOrderReq.order_no)
}

// int64 user_id = 2;
inline void QueryOrderReq::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::int64_t QueryOrderReq::user_id() const {
  // @@protoc_insertion_point(field_get:payment.QueryOrderReq.user_id)
  return _internal_user_id();
}
inline void QueryOrderReq::set_user_id(::int64_t value) {
  _internal_set_user_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:payment.QueryOrderReq.user_id)
}
inline ::int64_t QueryOrderReq::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_;
}
inline void QueryOrderReq::_internal_set_user_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = value;
}

// int64 last_id = 3;
inline void QueryOrderReq::clear_last_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.last_id_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::int64_t QueryOrderReq::last_id() const {
  // @@protoc_insertion_point(field_get:payment.QueryOrderReq.last_id)
  return _internal_last_id();
}
inline void QueryOrderReq::set_last_id(::int64_t value) {
  _internal_set_last_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:payment.QueryOrderReq.last_id)
}
inline ::int64_t QueryOrderReq::_internal_last_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.last_id_;
}
inline void QueryOrderReq::_internal_set_last_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.last_id_ = value;
}

// -------------------------------------------------------------------

// QueryOrderResp

// repeated .payment.Order list = 1;
inline int QueryOrderResp::_internal_list_size() const {
  return _internal_list().size();
}
inline int QueryOrderResp::list_size() const {
  return _internal_list_size();
}
inline void QueryOrderResp::clear_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.list_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::payment::Order& QueryOrderResp::list(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:payment.QueryOrderResp.list)
  return _internal_list().Get(index);
}
inline ::payment::Order* PROTOBUF_NONNULL QueryOrderResp::mutable_list(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:payment.QueryOrderResp.list)
  return _internal_mutable_list()->Mutable(index);
}
inline ::payment::Order* PROTOBUF_NONNULL QueryOrderResp::add_list()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::payment::Order* _add =
      _internal_mutable_list()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:payment.QueryOrderResp.list)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::payment::Order>& QueryOrderResp::list() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:payment.QueryOrderResp.list)
  return _internal_list();
}
inline ::google::protobuf::RepeatedPtrField<::payment::Order>* PROTOBUF_NONNULL
QueryOrderResp::mutable_list() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:payment.QueryOrderResp.list)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_list();
}
inline const ::google::protobuf::RepeatedPtrField<::payment::Order>&
QueryOrderResp::_internal_list() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.list_;
}
inline ::google::protobuf::RepeatedPtrField<::payment::Order>* PROTOBUF_NONNULL
QueryOrderResp::_internal_mutable_list() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.list_;
}

// bool has_more = 2;
inline void QueryOrderResp::clear_has_more() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.has_more_ = false;
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline bool QueryOrderResp::has_more() const {
  // @@protoc_insertion_point(field_get:payment.QueryOrderResp.has_more)
  return _internal_has_more();
}
inline void QueryOrderResp::set_has_more(bool value) {
  _internal_set_has_more(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:payment.QueryOrderResp.has_more)
}
inline bool QueryOrderResp::_internal_has_more() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.has_more_;
}
inline void QueryOrderResp::_internal_set_has_more(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.has_more_ = value;
}

// -------------------------------------------------------------------

// Order

// int64 id = 1;
inline void Order::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::int64_t Order::id() const {
  // @@protoc_insertion_point(field_get:payment.Order.id)
  return _internal_id();
}
inline void Order::set_id(::int64_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:payment.Order.id)
}
inline ::int64_t Order::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void Order::_internal_set_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// string order_no = 2;
inline void Order::clear_order_no() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_no_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& Order::order_no() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:payment.Order.order_no)
  return _internal_order_no();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Order::set_order_no(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.order_no_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:payment.Order.order_no)
}
inline ::std::string* PROTOBUF_NONNULL Order::mutable_order_no()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_order_no();
  // @@protoc_insertion_point(field_mutable:payment.Order.order_no)
  return _s;
}
inline const ::std::string& Order::_internal_order_no() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.order_no_.Get();
}
inline void Order::_internal_set_order_no(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_no_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Order::_internal_mutable_order_no() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.order_no_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Order::release_order_no() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:payment.Order.order_no)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.order_no_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.order_no_.Set("", GetArena());
  }
  return released;
}
inline void Order::set_allocated_order_no(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.order_no_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.order_no_.IsDefault()) {
    _impl_.order_no_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:payment.Order.order_no)
}

// int64 user_id = 3;
inline void Order::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::int64_t Order::user_id() const {
  // @@protoc_insertion_point(field_get:payment.Order.user_id)
  return _internal_user_id();
}
inline void Order::set_user_id(::int64_t value) {
  _internal_set_user_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:payment.Order.user_id)
}
inline ::int64_t Order::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_;
}
inline void Order::_internal_set_user_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = value;
}

// int64 money = 4;
inline void Order::clear_money() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.money_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline ::int64_t Order::money() const {
  // @@protoc_insertion_point(field_get:payment.Order.money)
  return _internal_money();
}
inline void Order::set_money(::int64_t value) {
  _internal_set_money(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:payment.Order.money)
}
inline ::int64_t Order::_internal_money() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.money_;
}
inline void Order::_internal_set_money(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.money_ = value;
}

// string currency = 5;
inline void Order::clear_currency() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.currency_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& Order::currency() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:payment.Order.currency)
  return _internal_currency();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Order::set_currency(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.currency_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:payment.Order.currency)
}
inline ::std::string* PROTOBUF_NONNULL Order::mutable_currency()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_currency();
  // @@protoc_insertion_point(field_mutable:payment.Order.currency)
  return _s;
}
inline const ::std::string& Order::_internal_currency() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.currency_.Get();
}
inline void Order::_internal_set_currency(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.currency_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Order::_internal_mutable_currency() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.currency_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Order::release_currency() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:payment.Order.currency)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.currency_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.currency_.Set("", GetArena());
  }
  return released;
}
inline void Order::set_allocated_currency(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.currency_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.currency_.IsDefault()) {
    _impl_.currency_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:payment.Order.currency)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace payment


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // payment_2fpayment_2eproto_2epb_2eh
