// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: payment/payment.proto
// Protobuf C++ Version: 7.36.0-dev

#include "payment/payment.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::payment::CreateOrderReq
        {&::_pbi::kDescriptorMethods, &::descriptor_table_payment_2fpayment_2eproto, /* tracker*/ nullptr,},
        // ::payment::CreateOrderResp
        {&::_pbi::kDescriptorMethods, &::descriptor_table_payment_2fpayment_2eproto, /* tracker*/ nullptr,},
        // ::payment::QueryOrderReq
        {&::_pbi::kDescriptorMethods, &::descriptor_table_payment_2fpayment_2eproto, /* tracker*/ nullptr,},
        // ::payment::QueryOrderResp
        {&::_pbi::kDescriptorMethods, &::descriptor_table_payment_2fpayment_2eproto, /* tracker*/ nullptr,},
        // ::payment::Order
        {&::_pbi::kDescriptorMethods, &::descriptor_table_payment_2fpayment_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace payment {
class QueryOrderReq::_Internal {
 public:
  using HasBits = decltype(::std::declval<QueryOrderReq>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(QueryOrderReq, _impl_._has_bits_);
};

constexpr QueryOrderReq::ParseTableT_ QueryOrderReq::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(QueryOrderReq, _impl_._has_bits_),
      0, // no _extensions_
      3, 24,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967288,  // skipmap
      offsetof(ParseTableT_, field_entries),
      3,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::payment::QueryOrderReq>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // string order_no = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(QueryOrderReq, _impl_.order_no_)}},
      // int64 user_id = 2;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(QueryOrderReq, _impl_.user_id_), 1>(),
       {16, 1, 0,
        PROTOBUF_FIELD_OFFSET(QueryOrderReq, _impl_.user_id_)}},
      // int64 last_id = 3;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(QueryOrderReq, _impl_.last_id_), 2>(),
       {24, 2, 0,
        PROTOBUF_FIELD_OFFSET(QueryOrderReq, _impl_.last_id_)}},
    }}, {{
      65535, 65535
    }}, {{
      // string order_no = 1;
      {PROTOBUF_FIELD_OFFSET(QueryOrderReq, _impl_.order_no_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // int64 user_id = 2;
      {PROTOBUF_FIELD_OFFSET(QueryOrderReq, _impl_.user_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
      // int64 last_id = 3;
      {PROTOBUF_FIELD_OFFSET(QueryOrderReq, _impl_.last_id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    }},
    // no aux_entries
    {{
      "\25\10\0\0\0\0\0\0"
      "payment.QueryOrderReq"
      "order_no"
    }},
  };
}


inline constexpr QueryOrderReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : order_no_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        user_id_{::int64_t{0}},
        last_id_{::int64_t{0}} {}

template <typename>
constexpr QueryOrderReq::QueryOrderReq(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL QueryOrderReq::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) QueryOrderReq(arena);
}
constexpr auto QueryOrderReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(QueryOrderReq), alignof(QueryOrderReq));
}
constexpr auto QueryOrderReq::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &QueryOrderReq::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<QueryOrderReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &QueryOrderReq::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<QueryOrderReq>(), &QueryOrderReq::ByteSizeLong,
              &QueryOrderReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(QueryOrderReq, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[2],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_payment_2fpayment_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct QueryOrderReqGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr QueryOrderReqGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 QueryOrderReq_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(QueryOrderReq::InternalGenerateClassData_(
            _default, &QueryOrderReq_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<QueryOrderReq>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~QueryOrderReqGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) QueryOrderReq _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<QueryOrderReq>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(QueryOrderReqGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST QueryOrderReqGlobalsTypeInternal QueryOrderReq_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* QueryOrderReq_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return QueryOrderReq_globals_.GetClassData();
#else
  return QueryOrderReq_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class Order::_Internal {
 public:
  using HasBits = decltype(::std::declval<Order>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Order, _impl_._has_bits_);
};

constexpr Order::ParseTableT_ Order::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(Order, _impl_._has_bits_),
      0, // no _extensions_
      5, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967264,  // skipmap
      offsetof(ParseTableT_, field_entries),
      5,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::payment::Order>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // int64 id = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Order, _impl_.id_), 2>(),
       {8, 2, 0,
        PROTOBUF_FIELD_OFFSET(Order, _impl_.id_)}},
      // string order_no = 2;
      {::_pbi::TcParser::FastUS1,
       {18, 0, 0,
        PROTOBUF_FIELD_OFFSET(Order, _impl_.order_no_)}},
      // int64 user_id = 3;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Order, _impl_.user_id_), 3>(),
       {24, 3, 0,
        PROTOBUF_FIELD_OFFSET(Order, _impl_.user_id_)}},
      // int64 money = 4;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Order, _impl_.money_), 4>(),
       {32, 4, 0,
        PROTOBUF_FIELD_OFFSET(Order, _impl_.money_)}},
      // string currency = 5;
      {::_pbi::TcParser::FastUS1,
       {42, 1, 0,
        PROTOBUF_FIELD_OFFSET(Order, _impl_.currency_)}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, {{
      // int64 id = 1;
      {PROTOBUF_FIELD_OFFSET(Order, _impl_.id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
      // string order_no = 2;
      {PROTOBUF_FIELD_OFFSET(Order, _impl_.order_no_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // int64 user_id = 3;
      {PROTOBUF_FIELD_OFFSET(Order, _impl_.user_id_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
      // int64 money = 4;
      {PROTOBUF_FIELD_OFFSET(Order, _impl_.money_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
      // string currency = 5;
      {PROTOBUF_FIELD_OFFSET(Order, _impl_.currency_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
      "\15\0\10\0\0\10\0\0"
      "payment.Order"
      "order_no"
      "currency"
    }},
  };
}


inline constexpr Order::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : order_no_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        currency_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{::int64_t{0}},
        user_id_{::int64_t{0}},
        money_{::int64_t{0}} {}

template <typename>
constexpr Order::Order(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL Order::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Order(arena);
}
constexpr auto Order::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Order), alignof(Order));
}
constexpr auto Order::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &Order::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Order>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Order::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Order>(), &Order::ByteSizeLong,
              &Order::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Order, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[4],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_payment_2fpayment_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct OrderGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr OrderGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 Order_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(Order::InternalGenerateClassData_(
            _default, &Order_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<Order>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~OrderGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) Order _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<Order>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(OrderGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST OrderGlobalsTypeInternal Order_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* Order_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return Order_globals_.GetClassData();
#else
  return Order_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class CreateOrderResp::_Internal {
 public:
};

constexpr CreateOrderResp::ParseTableT_ CreateOrderResp::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(CreateOrderResp,
                            _impl_._cached_size_),  // no hasbits
      0, // no _extensions_
      0, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967295,  // skipmap
      offsetof(ParseTableT_, field_names),  // no field_entries
      0,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::payment::CreateOrderResp>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, // no field_entries, or aux_entries
    {{
    }},
  };
}

template <typename>
constexpr CreateOrderResp::CreateOrderResp(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::internal::ZeroFieldsBase(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL CreateOrderResp::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CreateOrderResp(arena);
}
constexpr auto CreateOrderResp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CreateOrderResp), alignof(CreateOrderResp));
}
constexpr auto CreateOrderResp::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &CreateOrderResp::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<CreateOrderResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CreateOrderResp::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<CreateOrderResp>(), &CreateOrderResp::ByteSizeLong,
              &CreateOrderResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CreateOrderResp, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_payment_2fpayment_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct CreateOrderRespGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr CreateOrderRespGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 CreateOrderResp_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(CreateOrderResp::InternalGenerateClassData_(
            _default, &CreateOrderResp_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<CreateOrderResp>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~CreateOrderRespGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) CreateOrderResp _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<CreateOrderResp>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(CreateOrderRespGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST CreateOrderRespGlobalsTypeInternal CreateOrderResp_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* CreateOrderResp_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return CreateOrderResp_globals_.GetClassData();
#else
  return CreateOrderResp_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class CreateOrderReq::_Internal {
 public:
  using HasBits = decltype(::std::declval<CreateOrderReq>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CreateOrderReq, _impl_._has_bits_);
};

constexpr CreateOrderReq::ParseTableT_ CreateOrderReq::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(CreateOrderReq, _impl_._has_bits_),
      0, // no _extensions_
      4, 24,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967280,  // skipmap
      offsetof(ParseTableT_, field_entries),
      4,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::payment::CreateOrderReq>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // string currency = 4;
      {::_pbi::TcParser::FastUS1,
       {34, 1, 0,
        PROTOBUF_FIELD_OFFSET(CreateOrderReq, _impl_.currency_)}},
      // string order_no = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(CreateOrderReq, _impl_.order_no_)}},
      // int64 user_id = 2;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CreateOrderReq, _impl_.user_id_), 2>(),
       {16, 2, 0,
        PROTOBUF_FIELD_OFFSET(CreateOrderReq, _impl_.user_id_)}},
      // int64 money = 3;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CreateOrderReq, _impl_.money_), 3>(),
       {24, 3, 0,
        PROTOBUF_FIELD_OFFSET(CreateOrderReq, _impl_.money_)}},
    }}, {{
      65535, 65535
    }}, {{
      // string order_no = 1;
      {PROTOBUF_FIELD_OFFSET(CreateOrderReq, _impl_.order_no_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // int64 user_id = 2;
      {PROTOBUF_FIELD_OFFSET(CreateOrderReq, _impl_.user_id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
      // int64 money = 3;
      {PROTOBUF_FIELD_OFFSET(CreateOrderReq, _impl_.money_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
      // string currency = 4;
      {PROTOBUF_FIELD_OFFSET(CreateOrderReq, _impl_.currency_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
      "\26\10\0\0\10\0\0\0"
      "payment.CreateOrderReq"
      "order_no"
      "currency"
    }},
  };
}


inline constexpr CreateOrderReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : order_no_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        currency_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        user_id_{::int64_t{0}},
        money_{::int64_t{0}} {}

template <typename>
constexpr CreateOrderReq::CreateOrderReq(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL CreateOrderReq::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CreateOrderReq(arena);
}
constexpr auto CreateOrderReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CreateOrderReq), alignof(CreateOrderReq));
}
constexpr auto CreateOrderReq::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &CreateOrderReq::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CreateOrderReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CreateOrderReq::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CreateOrderReq>(), &CreateOrderReq::ByteSizeLong,
              &CreateOrderReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CreateOrderReq, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_payment_2fpayment_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct CreateOrderReqGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr CreateOrderReqGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 CreateOrderReq_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(CreateOrderReq::InternalGenerateClassData_(
            _default, &CreateOrderReq_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<CreateOrderReq>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~CreateOrderReqGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) CreateOrderReq _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<CreateOrderReq>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(CreateOrderReqGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST CreateOrderReqGlobalsTypeInternal CreateOrderReq_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* CreateOrderReq_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return CreateOrderReq_globals_.GetClassData();
#else
  return CreateOrderReq_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class QueryOrderResp::_Internal {
 public:
  using HasBits = decltype(::std::declval<QueryOrderResp>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(QueryOrderResp, _impl_._has_bits_);
};

constexpr QueryOrderResp::ParseTableT_ QueryOrderResp::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(QueryOrderResp, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      1,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::payment::QueryOrderResp>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // bool has_more = 2;
      {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(QueryOrderResp, _impl_.has_more_), 1>(),
       {16, 1, 0,
        PROTOBUF_FIELD_OFFSET(QueryOrderResp, _impl_.has_more_)}},
      // repeated .payment.Order list = 1;
      {::_pbi::TcParser::FastMtR1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(QueryOrderResp, _impl_.list_)}},
    }}, {{
      65535, 65535
    }}, {{
      // repeated .payment.Order list = 1;
      {PROTOBUF_FIELD_OFFSET(QueryOrderResp, _impl_.list_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
      // bool has_more = 2;
      {PROTOBUF_FIELD_OFFSET(QueryOrderResp, _impl_.has_more_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::payment::Order>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::payment::Order_globals_},
        #endif
    }},
    {{
    }},
  };
}


inline constexpr QueryOrderResp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : list_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::payment::QueryOrderResp,
            PROTOBUF_FIELD_OFFSET(::payment::QueryOrderResp, _impl_.list_)>()
         }
        ,
        has_more_{false} {}

template <typename>
constexpr QueryOrderResp::QueryOrderResp(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL QueryOrderResp::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) QueryOrderResp(arena);
}
constexpr auto QueryOrderResp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(QueryOrderResp), alignof(QueryOrderResp));
}
constexpr auto QueryOrderResp::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &QueryOrderResp::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<QueryOrderResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &QueryOrderResp::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<QueryOrderResp>(), &QueryOrderResp::ByteSizeLong,
              &QueryOrderResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(QueryOrderResp, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[3],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_payment_2fpayment_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct QueryOrderRespGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr QueryOrderRespGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 QueryOrderResp_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(QueryOrderResp::InternalGenerateClassData_(
            _default, &QueryOrderResp_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<QueryOrderResp>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~QueryOrderRespGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) QueryOrderResp _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<QueryOrderResp>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(QueryOrderRespGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST QueryOrderRespGlobalsTypeInternal QueryOrderResp_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* QueryOrderResp_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return QueryOrderResp_globals_.GetClassData();
#else
  return QueryOrderResp_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace payment
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_payment_2fpayment_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_payment_2fpayment_2eproto = nullptr;
const ::uint32_t
    TableStruct_payment_2fpayment_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::payment::CreateOrderReq, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::payment::CreateOrderReq, _impl_.order_no_),
        PROTOBUF_FIELD_OFFSET(::payment::CreateOrderReq, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::payment::CreateOrderReq, _impl_.money_),
        PROTOBUF_FIELD_OFFSET(::payment::CreateOrderReq, _impl_.currency_),
        0,
        2,
        3,
        1,
        0x000, // bitmap
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::payment::QueryOrderReq, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::payment::QueryOrderReq, _impl_.order_no_),
        PROTOBUF_FIELD_OFFSET(::payment::QueryOrderReq, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::payment::QueryOrderReq, _impl_.last_id_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::payment::QueryOrderResp, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::payment::QueryOrderResp, _impl_.list_),
        PROTOBUF_FIELD_OFFSET(::payment::QueryOrderResp, _impl_.has_more_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::payment::Order, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::payment::Order, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::payment::Order, _impl_.order_no_),
        PROTOBUF_FIELD_OFFSET(::payment::Order, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::payment::Order, _impl_.money_),
        PROTOBUF_FIELD_OFFSET(::payment::Order, _impl_.currency_),
        2,
        0,
        3,
        4,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::payment::CreateOrderReq)},
        {11, sizeof(::payment::CreateOrderResp)},
        {12, sizeof(::payment::QueryOrderReq)},
        {21, sizeof(::payment::QueryOrderResp)},
        {28, sizeof(::payment::Order)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::payment::CreateOrderReq_globals_,
        &::payment::CreateOrderResp_globals_,
        &::payment::QueryOrderReq_globals_,
        &::payment::QueryOrderResp_globals_,
        &::payment::Order_globals_,
};
const char descriptor_table_protodef_payment_2fpayment_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025payment/payment.proto\022\007payment\032\024common"
    "/message.proto\"T\n\016CreateOrderReq\022\020\n\010orde"
    "r_no\030\001 \001(\t\022\017\n\007user_id\030\002 \001(\003\022\r\n\005money\030\003 \001"
    "(\003\022\020\n\010currency\030\004 \001(\t\"\021\n\017CreateOrderResp\""
    "C\n\rQueryOrderReq\022\020\n\010order_no\030\001 \001(\t\022\017\n\007us"
    "er_id\030\002 \001(\003\022\017\n\007last_id\030\003 \001(\003\"@\n\016QueryOrd"
    "erResp\022\034\n\004list\030\001 \003(\0132\016.payment.Order\022\020\n\010"
    "has_more\030\002 \001(\010\"W\n\005Order\022\n\n\002id\030\001 \001(\003\022\020\n\010o"
    "rder_no\030\002 \001(\t\022\017\n\007user_id\030\003 \001(\003\022\r\n\005money\030"
    "\004 \001(\003\022\020\n\010currency\030\005 \001(\t2\206\001\n\016PaymentServi"
    "ce\0225\n\013CreateOrder\022\027.payment.CreateOrderR"
    "eq\032\r.common.Empty\022=\n\nQueryOrder\022\026.paymen"
    "t.QueryOrderReq\032\027.payment.QueryOrderResp"
    "b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_payment_2fpayment_2eproto_deps[1] = {
        &::descriptor_table_common_2fmessage_2eproto,
};
static ::absl::once_flag descriptor_table_payment_2fpayment_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_payment_2fpayment_2eproto = {
    false,
    false,
    528,
    descriptor_table_protodef_payment_2fpayment_2eproto,
    "payment/payment.proto",
    &descriptor_table_payment_2fpayment_2eproto_once,
    descriptor_table_payment_2fpayment_2eproto_deps,
    1,
    5,
    schemas,
    file_message_globals,
    TableStruct_payment_2fpayment_2eproto::offsets,
    file_level_enum_descriptors_payment_2fpayment_2eproto,
    file_level_service_descriptors_payment_2fpayment_2eproto,
};
namespace payment {
// ===================================================================

CreateOrderReq::CreateOrderReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CreateOrderReq_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:payment.CreateOrderReq)
}
PROTOBUF_NDEBUG_INLINE CreateOrderReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::payment::CreateOrderReq& from_msg)
      : _has_bits_{from._has_bits_},
        order_no_(arena, from.order_no_),
        currency_(arena, from.currency_) {}

CreateOrderReq::CreateOrderReq(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CreateOrderReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CreateOrderReq_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CreateOrderReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, user_id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, user_id_),
           offsetof(Impl_, money_) -
               offsetof(Impl_, user_id_) +
               sizeof(Impl_::money_));

  // @@protoc_insertion_point(copy_constructor:payment.CreateOrderReq)
}
PROTOBUF_NDEBUG_INLINE CreateOrderReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : order_no_(arena),
        currency_(arena) {}

inline void CreateOrderReq::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, user_id_),
           0,
           offsetof(Impl_, money_) -
               offsetof(Impl_, user_id_) +
               sizeof(Impl_::money_));
}
CreateOrderReq::~CreateOrderReq() {
  // @@protoc_insertion_point(destructor:payment.CreateOrderReq)
  SharedDtor(*this);
}
inline void CreateOrderReq::SharedDtor(MessageLite& self) {
  CreateOrderReq& this_ = static_cast<CreateOrderReq&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.order_no_.Destroy();
  this_._impl_.currency_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CreateOrderReq_class_data_ =
        CreateOrderReq::InternalGenerateClassData_(CreateOrderReq_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CreateOrderReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CreateOrderReq_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CreateOrderReq_class_data_.tc_table);
  return CreateOrderReq_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CreateOrderReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CreateOrderReq_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&CreateOrderReq_globals_));
  return CreateOrderReq_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const CreateOrderReq::ParseTableT_
    CreateOrderReq::_table_ =
        CreateOrderReq::InternalGenerateParseTable_(CreateOrderReq_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void CreateOrderReq::Clear() {
// @@protoc_insertion_point(message_clear_start:payment.CreateOrderReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.order_no_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.currency_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000cU)) {
    ::memset(&_impl_.user_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.money_) -
        reinterpret_cast<char*>(&_impl_.user_id_)) + sizeof(_impl_.money_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CreateOrderReq::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CreateOrderReq& this_ = static_cast<const CreateOrderReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CreateOrderReq::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CreateOrderReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:payment.CreateOrderReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string order_no = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_order_no().empty()) {
      const ::std::string& _s = this_._internal_order_no();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "payment.CreateOrderReq.order_no");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int64 user_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_user_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_user_id(), target);
    }
  }

  // int64 money = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_money() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
              stream, this_._internal_money(), target);
    }
  }

  // string currency = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_currency().empty()) {
      const ::std::string& _s = this_._internal_currency();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "payment.CreateOrderReq.currency");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:payment.CreateOrderReq)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CreateOrderReq::ByteSizeLong(const MessageLite& base) {
  const CreateOrderReq& this_ = static_cast<const CreateOrderReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CreateOrderReq::ByteSizeLong() const {
  const CreateOrderReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:payment.CreateOrderReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string order_no = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_order_no().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_order_no());
      }
    }
    // string currency = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_currency().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_currency());
      }
    }
    // int64 user_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_user_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_user_id());
      }
    }
    // int64 money = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_money() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_money());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CreateOrderReq::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<CreateOrderReq*>(&to_msg);
  auto& from = static_cast<const CreateOrderReq&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:payment.CreateOrderReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_order_no().empty()) {
        _this->_internal_set_order_no(from._internal_order_no());
      } else {
        if (_this->_impl_.order_no_.IsDefault()) {
          _this->_internal_set_order_no("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_currency().empty()) {
        _this->_internal_set_currency(from._internal_currency());
      } else {
        if (_this->_impl_.currency_.IsDefault()) {
          _this->_internal_set_currency("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_user_id() != 0) {
        _this->_impl_.user_id_ = from._impl_.user_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_money() != 0) {
        _this->_impl_.money_ = from._impl_.money_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CreateOrderReq::CopyFrom(const CreateOrderReq& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:payment.CreateOrderReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CreateOrderReq::InternalSwap(CreateOrderReq* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.order_no_, &other->_impl_.order_no_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.currency_, &other->_impl_.currency_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CreateOrderReq, _impl_.money_)
      + sizeof(CreateOrderReq::_impl_.money_)
      - PROTOBUF_FIELD_OFFSET(CreateOrderReq, _impl_.user_id_)>(
          reinterpret_cast<char*>(&_impl_.user_id_),
          reinterpret_cast<char*>(&other->_impl_.user_id_));
}

::google::protobuf::Metadata CreateOrderReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

CreateOrderResp::CreateOrderResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, CreateOrderResp_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:payment.CreateOrderResp)
}
CreateOrderResp::CreateOrderResp(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CreateOrderResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, CreateOrderResp_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CreateOrderResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:payment.CreateOrderResp)
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CreateOrderResp_class_data_ =
        CreateOrderResp::InternalGenerateClassData_(CreateOrderResp_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CreateOrderResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CreateOrderResp_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CreateOrderResp_class_data_.tc_table);
  return CreateOrderResp_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CreateOrderResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CreateOrderResp_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&CreateOrderResp_globals_));
  return CreateOrderResp_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const CreateOrderResp::ParseTableT_
    CreateOrderResp::_table_ =
        CreateOrderResp::InternalGenerateParseTable_(CreateOrderResp_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS







::google::protobuf::Metadata CreateOrderResp::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

QueryOrderReq::QueryOrderReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, QueryOrderReq_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:payment.QueryOrderReq)
}
PROTOBUF_NDEBUG_INLINE QueryOrderReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::payment::QueryOrderReq& from_msg)
      : _has_bits_{from._has_bits_},
        order_no_(arena, from.order_no_) {}

QueryOrderReq::QueryOrderReq(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const QueryOrderReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, QueryOrderReq_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  QueryOrderReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, user_id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, user_id_),
           offsetof(Impl_, last_id_) -
               offsetof(Impl_, user_id_) +
               sizeof(Impl_::last_id_));

  // @@protoc_insertion_point(copy_constructor:payment.QueryOrderReq)
}
PROTOBUF_NDEBUG_INLINE QueryOrderReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : order_no_(arena) {}

inline void QueryOrderReq::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, user_id_),
           0,
           offsetof(Impl_, last_id_) -
               offsetof(Impl_, user_id_) +
               sizeof(Impl_::last_id_));
}
QueryOrderReq::~QueryOrderReq() {
  // @@protoc_insertion_point(destructor:payment.QueryOrderReq)
  SharedDtor(*this);
}
inline void QueryOrderReq::SharedDtor(MessageLite& self) {
  QueryOrderReq& this_ = static_cast<QueryOrderReq&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.order_no_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull QueryOrderReq_class_data_ =
        QueryOrderReq::InternalGenerateClassData_(QueryOrderReq_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
QueryOrderReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&QueryOrderReq_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(QueryOrderReq_class_data_.tc_table);
  return QueryOrderReq_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
QueryOrderReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&QueryOrderReq_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&QueryOrderReq_globals_));
  return QueryOrderReq_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const QueryOrderReq::ParseTableT_
    QueryOrderReq::_table_ =
        QueryOrderReq::InternalGenerateParseTable_(QueryOrderReq_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void QueryOrderReq::Clear() {
// @@protoc_insertion_point(message_clear_start:payment.QueryOrderReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.order_no_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000006U)) {
    ::memset(&_impl_.user_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.last_id_) -
        reinterpret_cast<char*>(&_impl_.user_id_)) + sizeof(_impl_.last_id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL QueryOrderReq::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const QueryOrderReq& this_ = static_cast<const QueryOrderReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL QueryOrderReq::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const QueryOrderReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:payment.QueryOrderReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string order_no = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_order_no().empty()) {
      const ::std::string& _s = this_._internal_order_no();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "payment.QueryOrderReq.order_no");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int64 user_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_user_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_user_id(), target);
    }
  }

  // int64 last_id = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_last_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
              stream, this_._internal_last_id(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:payment.QueryOrderReq)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t QueryOrderReq::ByteSizeLong(const MessageLite& base) {
  const QueryOrderReq& this_ = static_cast<const QueryOrderReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t QueryOrderReq::ByteSizeLong() const {
  const QueryOrderReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:payment.QueryOrderReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string order_no = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_order_no().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_order_no());
      }
    }
    // int64 user_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_user_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_user_id());
      }
    }
    // int64 last_id = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_last_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_last_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void QueryOrderReq::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<QueryOrderReq*>(&to_msg);
  auto& from = static_cast<const QueryOrderReq&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:payment.QueryOrderReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_order_no().empty()) {
        _this->_internal_set_order_no(from._internal_order_no());
      } else {
        if (_this->_impl_.order_no_.IsDefault()) {
          _this->_internal_set_order_no("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_user_id() != 0) {
        _this->_impl_.user_id_ = from._impl_.user_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_last_id() != 0) {
        _this->_impl_.last_id_ = from._impl_.last_id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void QueryOrderReq::CopyFrom(const QueryOrderReq& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:payment.QueryOrderReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void QueryOrderReq::InternalSwap(QueryOrderReq* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.order_no_, &other->_impl_.order_no_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(QueryOrderReq, _impl_.last_id_)
      + sizeof(QueryOrderReq::_impl_.last_id_)
      - PROTOBUF_FIELD_OFFSET(QueryOrderReq, _impl_.user_id_)>(
          reinterpret_cast<char*>(&_impl_.user_id_),
          reinterpret_cast<char*>(&other->_impl_.user_id_));
}

::google::protobuf::Metadata QueryOrderReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

QueryOrderResp::QueryOrderResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, QueryOrderResp_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:payment.QueryOrderResp)
}
PROTOBUF_NDEBUG_INLINE QueryOrderResp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::payment::QueryOrderResp& from_msg)
      : _has_bits_{from._has_bits_},
        list_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::payment::QueryOrderResp,
              PROTOBUF_FIELD_OFFSET(::payment::QueryOrderResp, _impl_.list_)>()
          , from.list_
        }
     {}

QueryOrderResp::QueryOrderResp(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const QueryOrderResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, QueryOrderResp_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  QueryOrderResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.has_more_ = from._impl_.has_more_;

  // @@protoc_insertion_point(copy_constructor:payment.QueryOrderResp)
}
PROTOBUF_NDEBUG_INLINE QueryOrderResp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : list_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::payment::QueryOrderResp,
            PROTOBUF_FIELD_OFFSET(::payment::QueryOrderResp, _impl_.list_)>()
         }
     {}

inline void QueryOrderResp::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.has_more_ = {};
}
QueryOrderResp::~QueryOrderResp() {
  // @@protoc_insertion_point(destructor:payment.QueryOrderResp)
  SharedDtor(*this);
}
inline void QueryOrderResp::SharedDtor(MessageLite& self) {
  QueryOrderResp& this_ = static_cast<QueryOrderResp&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull QueryOrderResp_class_data_ =
        QueryOrderResp::InternalGenerateClassData_(QueryOrderResp_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
QueryOrderResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&QueryOrderResp_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(QueryOrderResp_class_data_.tc_table);
  return QueryOrderResp_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
QueryOrderResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&QueryOrderResp_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&QueryOrderResp_globals_));
  return QueryOrderResp_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const QueryOrderResp::ParseTableT_
    QueryOrderResp::_table_ =
        QueryOrderResp::InternalGenerateParseTable_(QueryOrderResp_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void QueryOrderResp::Clear() {
// @@protoc_insertion_point(message_clear_start:payment.QueryOrderResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.list_.Clear();
  }
  _impl_.has_more_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL QueryOrderResp::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const QueryOrderResp& this_ = static_cast<const QueryOrderResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL QueryOrderResp::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const QueryOrderResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:payment.QueryOrderResp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .payment.Order list = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_list_size());
         i < n; i++) {
      const auto& repfield = this_._internal_list().Get(i);
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          1, repfield, repfield.GetCachedSize(), target,
          stream);
    }
  }

  // bool has_more = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_has_more() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          2, this_._internal_has_more(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:payment.QueryOrderResp)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t QueryOrderResp::ByteSizeLong(const MessageLite& base) {
  const QueryOrderResp& this_ = static_cast<const QueryOrderResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t QueryOrderResp::ByteSizeLong() const {
  const QueryOrderResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:payment.QueryOrderResp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated .payment.Order list = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_list_size();
      for (const auto& msg : this_._internal_list()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // bool has_more = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_has_more() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void QueryOrderResp::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<QueryOrderResp*>(&to_msg);
  auto& from = static_cast<const QueryOrderResp&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:payment.QueryOrderResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_list()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_list());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_has_more() != 0) {
        _this->_impl_.has_more_ = from._impl_.has_more_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void QueryOrderResp::CopyFrom(const QueryOrderResp& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:payment.QueryOrderResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void QueryOrderResp::InternalSwap(QueryOrderResp* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.list_.InternalSwap(&other->_impl_.list_);
  swap(_impl_.has_more_, other->_impl_.has_more_);
}

::google::protobuf::Metadata QueryOrderResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

Order::Order(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Order_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:payment.Order)
}
PROTOBUF_NDEBUG_INLINE Order::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::payment::Order& from_msg)
      : _has_bits_{from._has_bits_},
        order_no_(arena, from.order_no_),
        currency_(arena, from.currency_) {}

Order::Order(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Order& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Order_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Order* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, money_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::money_));

  // @@protoc_insertion_point(copy_constructor:payment.Order)
}
PROTOBUF_NDEBUG_INLINE Order::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : order_no_(arena),
        currency_(arena) {}

inline void Order::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, money_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::money_));
}
Order::~Order() {
  // @@protoc_insertion_point(destructor:payment.Order)
  SharedDtor(*this);
}
inline void Order::SharedDtor(MessageLite& self) {
  Order& this_ = static_cast<Order&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.order_no_.Destroy();
  this_._impl_.currency_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Order_class_data_ =
        Order::InternalGenerateClassData_(Order_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Order::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Order_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Order_class_data_.tc_table);
  return Order_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Order::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Order_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&Order_globals_));
  return Order_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const Order::ParseTableT_
    Order::_table_ =
        Order::InternalGenerateParseTable_(Order_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void Order::Clear() {
// @@protoc_insertion_point(message_clear_start:payment.Order)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.order_no_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.currency_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001cU)) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.money_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.money_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Order::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Order& this_ = static_cast<const Order&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Order::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Order& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:payment.Order)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int64 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_id(), target);
    }
  }

  // string order_no = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_order_no().empty()) {
      const ::std::string& _s = this_._internal_order_no();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "payment.Order.order_no");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // int64 user_id = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_user_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
              stream, this_._internal_user_id(), target);
    }
  }

  // int64 money = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_money() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<4>(
              stream, this_._internal_money(), target);
    }
  }

  // string currency = 5;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_currency().empty()) {
      const ::std::string& _s = this_._internal_currency();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "payment.Order.currency");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:payment.Order)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Order::ByteSizeLong(const MessageLite& base) {
  const Order& this_ = static_cast<const Order&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Order::ByteSizeLong() const {
  const Order& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:payment.Order)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // string order_no = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_order_no().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_order_no());
      }
    }
    // string currency = 5;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_currency().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_currency());
      }
    }
    // int64 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_id());
      }
    }
    // int64 user_id = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_user_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_user_id());
      }
    }
    // int64 money = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_money() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_money());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Order::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<Order*>(&to_msg);
  auto& from = static_cast<const Order&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:payment.Order)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_order_no().empty()) {
        _this->_internal_set_order_no(from._internal_order_no());
      } else {
        if (_this->_impl_.order_no_.IsDefault()) {
          _this->_internal_set_order_no("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_currency().empty()) {
        _this->_internal_set_currency(from._internal_currency());
      } else {
        if (_this->_impl_.currency_.IsDefault()) {
          _this->_internal_set_currency("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_user_id() != 0) {
        _this->_impl_.user_id_ = from._impl_.user_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_money() != 0) {
        _this->_impl_.money_ = from._impl_.money_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Order::CopyFrom(const Order& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:payment.Order)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Order::InternalSwap(Order* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.order_no_, &other->_impl_.order_no_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.currency_, &other->_impl_.currency_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Order, _impl_.money_)
      + sizeof(Order::_impl_.money_)
      - PROTOBUF_FIELD_OFFSET(Order, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata Order::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace payment
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_payment_2fpayment_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
